### ISSUE TITLE
application not running after configure

### ISSUE THREAD

**Issue by flik** [frogprincess/Lilypad-Zend-Framework-Blog#1]
Getting errors:

Notice: Undefined index: recaptcha in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\application\Bootstrap.php on line 16

Notice: Undefined index: message in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\application\Bootstrap.php on line 17

Notice: Undefined index: db in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\application\Bootstrap.php on line 19

Fatal error: Uncaught Zend_Db_Exception: Adapter parameters must be in an array or a Zend_Config object in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Db.php:223 Stack trace: #0 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\application\Bootstrap.php(19): Zend_Db::factory('PDO_MYSQL', NULL) #1 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(666): Bootstrap->_initAutoload() #2 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(619): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('autoload') #3 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(583): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('autoload') #4 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application.php(355): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL) #5 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\public\index.php(29): Zend_Application->boo in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Db.php on line 223

**Comment by flik** [comment]
Warning: include_once(Imixer\Controller\Plugin\LayoutModuleSwitcher.php): failed to open stream: No such file or directory in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Loader.php on line 146

Warning: include_once(): Failed opening 'Imixer\Controller\Plugin\LayoutModuleSwitcher.php' for inclusion (include_path='D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\application/../library;D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library;D:\xampp\php\PEAR') in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Loader.php on line 146

Fatal error: Uncaught Error: Class 'Imixer\Controller\Plugin\LayoutModuleSwitcher' not found in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Resource\Frontcontroller.php:111 Stack trace: #0 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(680): Zend_Application_Resource_Frontcontroller->init() #1 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(626): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('frontController') #2 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(583): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('frontController') #3 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\application\Bootstrap.php(37): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap('frontController') #4 D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Bootstrap\BootstrapAbstract.php(666): Bootstrap->_initSiteModul in D:\xampp\htdocs\Lilypad-Zend-Framework-Blog\library\Zend\Application\Resource\Frontcontroller.php on line 111
